/*view product*/

export const REQUEST_DATA_PRODUCT = 'REQUEST_DATA_PRODUCT'
export const SUCCESS = 'SUCCESS'
export const FAILED = 'FAILED'

/**** */

/***view brand */

export const REQUEST_DATA_BRAND = 'REQUEST_DATA_BRAND'
export const REQUEST_DATA_BRAND_SUCCESS = 'REQUEST_DATA_BRAND_SUCCESS'
export const REQUEST_DATA_BRAND_FAILURE = 'REQUEST_DATA_BRAND_FAILURE'

/**banner */

export const REQUEST_DATA_BANNER = 'REQUEST_DATA_BANNER'
export const REQUEST_DATA_BANNER_SUCCESS = 'REQUEST_DATA_BANNER_SUCCESS'
export const REQUEST_DATA_BANNER_FAILURE = 'REQUEST_DATA_BANNER_FAILURE'